### ISSUE TITLE
Heading error

### ISSUE THREAD

**Issue by Nuwanthi** [joielechong/CountryCodePicker#18]
There's a small spelling mistake in the dialog. "Select county" instead of "Select country" . Is there any way to change the heading without changing the library?

**Comment by joielechong** [comment]
I have fix the typo and updated the library to version 2.1.8. Can you test it? Don't forget that the library now need implicit dependencies:

    // dependencies for countrycodepicker
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'io.michaelrocks:libphonenumber-android:8.8.5'

    implementation 'com.github.joielechong:countrycodepicker:2.1.8'

**Comment by Akhrorjon** [comment]
Good time of the day


I have already saw your updates thanks for that. But actually, I want to customize the string select_country because in my app there are several languages (English, Uzbek, Russian), depends on the language chosen I would like to change that string (select_country). Do you have any solution for this. Thanks for taking my question into consideration.


Best regards

Akhrorjon

________________________________
От: Joielechong <notifications@github.com>
Отправлено: 20 апреля 2018 г. 22:52
Кому: joielechong/CountryCodePicker
Копия: Akhrorjon Aliev; Comment
Тема: Re: [joielechong/CountryCodePicker] Heading error (#18)


I have fix the typo and updated the library to version 2.1.8. Can you test it? Don't forget that the library now need implicit dependencies:

// dependencies for countrycodepicker
implementation 'com.android.support:recyclerview-v7:27.0.2'
implementation 'com.android.support:appcompat-v7:27.0.2'
implementation 'io.michaelrocks:libphonenumber-android:8.8.5'

implementation 'com.github.joielechong:countrycodepicker:2.1.8'


-

**Comment by joielechong** [comment]
You can easily override the text by adding an exact string resource name:

      <string name="select_country">Select specific country</string>

you need to add each string to the each values folder like in the values-br, values_ru, etc.

**Comment by joielechong** [comment]
I think this issue is solved. Please reopen again if not solved.

**Comment by zoro238** [comment]
Failed to resolve: com.github.joielechong:countrycodepicker:2.1.8

whats solve ???
