### ISSUE TITLE
onCountrySelectedIsCalledTooManyTimes

### ISSUE THREAD

**Issue by RISHABHPATNI1108** [joielechong/CountryCodePicker#38]
When I am adding a listner onCountry selected keeps running for too many times and crashes the app. what I am trying to do is if I select a country the country code automaticaly gets selected or vice versa

**Comment by joielechong** [comment]
It seems that you have introducing a circular dependencies for both of the listener and the country code view. The simplest hack is by using a boolean variable as a flag to differentiate if listener need to be called.

Because this issue is already to old (Though this is because of my laziness), I'll close this for now. Just re-open the issue if you want to discuss about the problem.
