### ISSUE TITLE
Edittext hint changes when using registerPhoneNumberTextView()

### ISSUE THREAD

**Issue by karanjhinga** [joielechong/CountryCodePicker#64]
whenever i am using registerPhoneNumberTextView() on country code picker view hint text changes. it changes hint to 081234 56789.

**Comment by joielechong** [comment]
It's because the default selected country in ccp is Indonesia. So, the hint is correct.

You need to set the default select country code with `ccp_defaultNameCode` attribute. For example: to make Argentina as the default country, add ccp_defaultNameCode="ar". Something like this:

```
  <com.rilixtech.widget.countrycodepicker.CountryCodePicker
      android:id="@+id/ccp"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_centerInParent="true"
      app:ccp_hideNameCode="false"
      app:ccp_hidePhoneCode="false"
      app:ccp_defaultNameCode="ar"
      app:ccp_keyboardAutoPopOnSearch="false"
      app:ccp_showFullName="false"
      />
```

The country code is Alpha-2 code from ISO_3166-1. See https://en.wikipedia.org/wiki/ISO_3166-1
